name: Test All Triggers

on:
  # 1. 手動実行トリガー
  workflow_dispatch:

  # 2. スケジュール実行トリガー
  schedule:
    - cron: '0 0 * * *' # 毎日0時（UTC）に実行

  # 3. プッシュイベントトリガー
  push:
    branches:
      - main
    tags:
      - v*

  # 4. プルリクエストイベントトリガー
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

  # 5. リポジトリディスパッチイベントトリガー
  repository_dispatch:
    types:
      - custom_event

  # 6. リリースイベントトリガー
  release:
    types:
      - published
      - edited
      - deleted

  # 7. ワークフロー実行イベントトリガー
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed

  # 8. イシューイベントトリガー
  issues:
    types:
      - opened
      - edited
      - deleted

  # 9. ラベルイベントトリガー
  label:
    types:
      - created
      - deleted

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Trigger Event
        run: |
          echo "1 Triggered by: ${{ github.event_name }}"
          echo "Event payload: ${{ toJson(github.event) }}"